-d D:\_FPGA\WAVPlayer\impl\gwsynthesis\WAVPlayer.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AC1/I0
-cst D:\_FPGA\WAVPlayer\src\WAVPlayer.cst
-cfg D:\_FPGA\WAVPlayer\impl\pnr\device.cfg
-sdc D:\_FPGA\WAVPlayer\src\WAVPlayer.sdc
-gao_crc 1000101101011000
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
-rtl_gao
